version: '3.3'

services:
  app:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    privileged: true
    restart: always
    ports:
      - '172.17.0.1:20580:5000'
    volumes:
      - ./app:/app